# -*- coding: utf-8 -*-
"""AND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROAA1f6XO3hp802pro1GAhiyy0Cj_ayp
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# 1. Create truth table data for the AND gate
# The output is 1 only when both inputs are 1
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])

labels = np.array([0, 0, 0, 1]) # Expected outputs for AND gate

# 2. Initialize a sequential neural network model
model = Sequential()

# 3. Add a hidden layer (2 neurons, input_dim=2, activation='sigmoid')
model.add(Dense(2, input_dim=2, activation='sigmoid'))

# 4. Add an output layer (1 neuron, activation='sigmoid')
model.add(Dense(1, activation='sigmoid'))

# 5. Compile the model
sgd = SGD(learning_rate=0.1)
model.compile(loss='mean_squared_error', optimizer=sgd)

# 6. Train the model
print("AND Gate Training started...")
model.fit(data, labels, epochs=3, verbose=0)
print("Training completed!\n")

# --- Prediction Code ---
predictions = model.predict(data)

print("--- AND Predictions ---")
for i in range(4):
    raw_val = predictions[i][0]
    rounded_val = round(raw_val)
    print(f"Input: {data[i]} -> Output Value: {raw_val:.4f} -> Final Gate Output: {rounded_val}")