# -*- coding: utf-8 -*-
"""XOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184uoPN3wo0nHEj085r61j-lzKBh7E7Ie
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# XOR gate truth table
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])

labels = np.array([0, 1, 1, 0])

# Create a sequential neural network model
model = Sequential()

#Add a hidden layer with 2 neurons and input layer with 2 neurons
model.add(Dense(2, input_dim=2, activation='sigmoid'))

# Add an output layer with 1 neuron
model.add(Dense(1, activation='sigmoid'))

# Compile the model
sgd = SGD(learning_rate=0.1)
model.compile(loss='mean_squared_error', optimizer=sgd)

# Train the model
epochs = 10000
model.fit(data, labels, epochs=3, verbose=0)

# Evaluate the model
print("Training completed. Evaluating the model...\n")

for i in range(len(data)):
    input_data = data[i].reshape(1, 2)
    predicted_label = model.predict(input_data)[0][0].round()
    print(f"Input: {data[i]}, Predicted Output: {predicted_label}")