# -*- coding: utf-8 -*-
"""GOOGLE_PLAYSTORE-CASE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1XMXmlx8rb_FaXrbCx90-SG7c8FP94m
"""

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv("/content/sample_data/googleplaystore_v2 (2).csv")

# Data Cleaning
df = df.dropna(subset=["Rating"])
df["Price"] = df["Price"].astype(str).str.replace("$","",regex=False)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

df["Installs"] = df["Installs"].astype(str).str.replace(",","",regex=False).str.replace("+","",regex=False)
df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

df.dropna(subset=["Price","Reviews","Installs"], inplace=True)
# Basic Information
print(df.head())
print(df.shape)
print(df.describe())

# Histogram
plt.hist(df["Rating"])
plt.title("Rating Histogram")
plt.show()

# Box Plot
plt.boxplot(df["Price"])
plt.title("Price Boxplot")
plt.show()

# Scatter Plot
plt.scatter(df["Price"], df["Rating"])
plt.xlabel("Price")
plt.ylabel("Rating")
plt.show()

# Bar Plot
sns.barplot(x="Content Rating", y="Rating", data=df)
plt.xticks(rotation=45)
plt.show()

# Heatmap
sns.heatmap(df[["Rating","Reviews","Price","Installs"]].corr(), annot=True)
plt.show()